# Generated by Django 4.0.5 on 2022-07-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_venue', models.CharField(max_length=100)),
                ('event_pic', models.ImageField(upload_to='event_pic')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
