# Generated by Django 4.0.5 on 2022-06-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_price', models.FloatField()),
                ('product_qty', models.IntegerField()),
                ('product_desc', models.TextField()),
                ('product_creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
