# Generated by Django 4.0.5 on 2022-06-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=25)),
                ('country_code', models.IntegerField()),
                ('country_cap', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
